### ISSUE TITLE
Перевод целей сломан

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1258]
### Описание

Нужно протестить какие переводы сломаны, как минимум cargo shuttle console board не переводит.

проверять давая цели командой:
addobjective [твой сикей] CargoShuttleCircuitboardStealObjective

Список целей:

```
type: objective
  id: CaptainIDStealObjective
  issuer: syndicate
  difficultyOverride: 2.75
  requirements:
    - !type:TraitorRequirement {}
    - !type:IncompatibleConditionsRequirement
      conditions:
        - DieCondition
    - !type:NotRoleRequirement
      roleId: Captain
  conditions:
    - !type:StealCondition
      prototype: CaptainIDCard

- type: objective
  id: KillRandomObjective
  issuer: syndicate
  requirements:
    - !type:TraitorRequirement {}
    - !type:IncompatibleConditionsRequirement
        conditions:
          - RandomTraitorAliveCondition
  conditions:
    - !type:KillRandomPersonCondition {}
  canBeDuplicate: true

- type: objective
  id: RandomTraitorAliveObjective
  issuer: syndicate
  requirements:
    - !type:TraitorRequirement {}
    - !type:IncompatibleConditionsRequirement
        conditions:
          - KillRandomPersonCondition
    - !type:MultipleTraitorsRequirement
  conditions:
    - !type:RandomTraitorAliveCondition {}
  canBeDuplicate: true

- type: objective
  id: DieObjective
  issuer: syndicate
  requirements:
    - !type:TraitorRequirement {}
    - !type:IncompatibleConditionsRequirement
      conditions:
        - StealCondition
        - EscapeShuttleCondition
  conditions:
    - !type:DieCondition {}

- type: objective
  id: CMOHyposprayStealObjective
  issuer: syndicate
  difficultyOverride: 2.75
  requirements:
    - !type:TraitorRequirement {}
    - !type:IncompatibleConditionsRequirement
      conditions:
        - DieCondition
    - !type:NotRoleRequirement
      roleId: ChiefMedicalOfficer
  conditions:
    - !type:StealCondition
      prototype: Hypospray
      owner: job-name-cmo

- type: objective
  id: RDHardsuitStealObjective
  issuer: syndicate
  difficultyOverride: 2.75
  requirements:
    - !type:TraitorRequirement {}
    - !type:IncompatibleConditionsRequirement
      conditions:
        - DieCondition
    - !type:NotRoleRequirement
      roleId: ResearchDirector
  conditions:
    - !type:StealCondition
      prototype: ClothingOuterHardsuitRd
      owner: job-name-rd

- type: objective
  id: HandTeleporterStealObjective
  issuer: syndicate
  difficultyOverride: 2.75
  requirements:
  - !type:TraitorRequirement {}
  - !type:IncompatibleConditionsRequirement
    conditions:
    - DieCondition
  - !type:NotRoleRequirement
    roleId: ResearchDirector
  conditions:
  - !type:StealCondition
    prototype: HandTeleporter
    owner: job-name-rd

- type: objective
  id: NukeDiskStealObjective
  issuer: syndicate
  requirements:
    - !type:TraitorRequirement {}
    - !type:IncompatibleConditionsRequirement
      conditions:
        - DieCondition
    - !type:NotRoleRequirement
      roleId: Captain
    - !type:NotRoleRequirement
      roleId: HeadOfSecurity
    - !type:NotRoleRequirement
      roleId: HeadOfPersonnel
    - !type:NotRoleRequirement
      roleId: ChiefEngineer
    - !type:NotRoleRequirement
      roleId: ChiefMedicalOfficer
    - !type:NotRoleRequirement
      roleId: ResearchDirector
  conditions:
    - !type:StealCondition
      prototype: NukeDisk
      owner: objective-condition-steal-station


- type: objective
  id: IDComputerBoardStealObjective
  issuer: syndicate
  requirements:
    - !type:TraitorRequirement {}
    - !type:IncompatibleConditionsRequirement
      conditions:
        - DieCondition
    - !type:NotRoleRequirement
      roleId: HeadOfPersonnel
  conditions:
    - !type:StealCondition
      prototype: IDComputerCircuitboard
      owner: job-name-hop

- type: objective
  id: MagbootsStealObjective
  issuer: syndicate
  difficultyOverride: 2.75
  requirements:
    - !type:TraitorRequirement {}
    - !type:IncompatibleConditionsRequirement
      conditions:
        - DieCondition
    - !type:NotRoleRequirement
      roleId: ChiefEngineer
  conditions:
    - !type:StealCondition
      prototype: ClothingShoesBootsMagAdv
      owner: job-name-ce

- type: objective
  id: SupplyConsoleBoardStealObjective
  issuer: syndicate
  requirements:
    - !type:TraitorRequirement {}
    - !type:IncompatibleConditionsRequirement
      conditions:
        - DieCondition
    - !type:NotRoleRequirement
      roleId: Quartermaster
  conditions:
    - !type:StealCondition
      prototype: CargoRequestComputerCircuitboard
      owner: job-name-qm

- type: objective
  id: CorgiMeatStealObjective
  issuer: syndicate
  requirements:
    - !type:TraitorRequirement {}
    - !type:IncompatibleConditionsRequirement
      conditions:
        - DieCondition
    - !type:NotRoleRequirement
      roleId: HeadOfPersonnel
  conditions:
    - !type:StealCondition
      prototype: FoodMeatCorgi
      owner: objective-condition-steal-Ian

- type: objective
  id: CaptainGunStealObjective
  issuer: syndicate
  difficultyOverride: 2.75
  requirements:
    - !type:TraitorRequirement {}
    - !type:IncompatibleConditionsRequirement
      conditions:
        - DieCondition
    - !type:NotRoleRequirement
      roleId: Captain
  conditions:
    - !type:StealCondition
      prototype: WeaponAntiqueLaser
      owner: job-name-captain

- type: objective
  id: CaptainJetpackStealObjective
  issuer: syndicate
  difficultyOverride: 2.75
  requirements:
    - !type:TraitorRequirement {}
    - !type:IncompatibleConditionsRequirement
      conditions:
        - DieCondition
    - !type:NotRoleRequirement
      roleId: Captain
  conditions:
    - !type:StealCondition
      prototype: JetpackCaptainFilled

- type: objective
  id: EscapeShuttleObjective
  issuer: syndicate
  requirements:
    - !type:TraitorRequirement {}
    - !type:IncompatibleConditionsRequirement
      conditions:
        - DieCondition
  conditions:
    - !type:EscapeShuttleCondition {}

- type: objective
  id: RandomTraitorProgressObjective
  issuer: syndicate
  requirements:
    - !type:TraitorRequirement {}
    - !type:MultipleTraitorsRequirement
  conditions:
    - !type:RandomTraitorProgressCondition {}
  canBeDuplicate: true
```

### Шаги воспроизведения

проверять давая цели командой:
addobjective [твой сикей] CargoShuttleCircuitboardStealObjective

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/220ea1bd-790e-4b78-a2c9-19b419cfdafd)
