### ISSUE TITLE
Сломанное наложение слоёв через clothingVisuals на расы (!= не человек)

### ISSUE THREAD

**Issue by EstKemran** [SerbiaStrong-220/space-station-14#2286]
### Описание

Для наложение слоёв у нас используется `clothingVisuals` в компоненте `Clothing`. С основной функцией, _наложение state_, оно справляется, но проблема возникает, если одеть одежду с `clothingVisuals` на другую расу.

На примере с макакой:
У разноцветных комбинезонов накладываются два стейта: `equipped-INNERCLOTHING` и `trinkets-equipped-INNERCLOTHING`, иногда и `prisoner-equipped-INNERCLOTHING`. Собственно, на макак спрайты не отображаются (отображается спрайт человека),  поэтому их не стали рисовать.
```  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuit/color.rsi
    clothingVisuals:
      jumpsuit:
      - state: equipped-INNERCLOTHING
      - state: trinkets-alt-equipped-INNERCLOTHING
```

На примере с воксами, скафандрами и шейдерами:
Если через тот же клозингвизуалс накладывать стейт с шейдером:
```
    sprite: SS220/Clothing/OuterClothing/Hardsuits/spatio.rsi
    clothingVisuals:
      outerClothing:
      - state: equipped-OUTERCLOTHING
      - state: equipped-OUTERCLOTHING-unshaded
        shader: unshaded
```
То, на человеке отображаются стейты с шейдером. На воксе, у которого есть свои спрайты, не только не отображаются стейст шейдером, но и основной спрайт. 
![367593702-1d826935-d2a7-421f-bd8f-7d7389e87eba](https://github.com/user-attachments/assets/cb29122c-bc62-4413-8874-bc375e087301)

Подробнее о проблеме с скафандрами, воксами и шейдером в ПРе:  Salvage Hardsuit Repsrite #1869 

### Шаги воспроизведения

1. Добавить компоненту `Clothing` `clothingVisuals` . Добавить спрайт для наложения на первый стайт.
2. Увидеть, что на расах, отличных от человека, неправильно отображаются стейты.
