### ISSUE TITLE
Ошибка в пресетах хамелеона глав

### ISSUE THREAD

**Issue by Alwayswannahunt** [SerbiaStrong-220/space-station-14#3057]
### Описание

В пресетах хамелеона для глав по умолчанию включён МЩ, нужно исправить под наш билд

**Comment by Alwayswannahunt** [comment]
> в импланте хамелеона за 3тк настоящий мщ помимо контроля хамелеона. Если ставить этому импланту фейковый мщ (4тк) то, набор целый с этим имплантом (3тк) будет дешевле самого импланта (4тк). А если колоть фейковый мщ, то он как и должен включается на пресетах с мщ и выключается на пресетах без мщ, тут по моему всё правильно.

Ты ваще о чём? Ещё раз прочти, пожалуйста, что написано

**Comment by Alwayswannahunt** [comment]
> так что исправлять то? Вместе с имплантом хамелеона колится настоящий имплант мщ, который не выключается и на других пресетах. Исправить чтоб он колол фейк мщ. который можно выключить? Тогда набор хамелеона с имплантом будет дешевле чем сам имплант. Я вообще не понимаю что ты имеешь в виду

Вот кусок кода пресета хамелеона для глав

```yml
- type: chameleonOutfit
  id: QuartermasterChameleonOutfit
  job: Quartermaster
  hasMindShield: true
  equipment:
    head: ClothingHeadHatQMsoft
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterQM
    neck: ClothingNeckCloakQm
    gloves: ClothingHandsKnuckleDustersQM
```
Это для КМа, у КМа у нас нету МЩ. Теперь смотрим на пресет хамелеона:

`  hasMindShield: true`

Эту строчку нужно убрать, поэтому итоговый пресет:
```yml
- type: chameleonOutfit
  id: QuartermasterChameleonOutfit
  job: Quartermaster
  equipment:
    head: ClothingHeadHatQMsoft
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterQM
    neck: ClothingNeckCloakQm
    gloves: ClothingHandsKnuckleDustersQM
```

И так по всем пресетам глав, окда?
