### ISSUE TITLE
Оранжевый шарф

### ISSUE THREAD

**Issue by AnkhaCats** [SerbiaStrong-220/space-station-14#3096]
### Описание

Оранжевый шарф «держит температуру» аналогично зимней куртке или зимним ботинкам

Как найти тот самый оранжевый шарф - я не знаю, но не думаю, что в щитспавне много оранжевых шарфов, поэтому проблем с поиском не будет  

### Шаги воспроизведения

Смотреть код оранжевого шарфа 
Всем шарфам убрали тепловой резист, а про этот либо забыли, либо оставили как фичу

**Comment by EstKemran** [comment]
Единственный оранжевый шарф, но у него нет каких-либо компонентов, связанных с температурой:
```
- type: entity
  parent: ClothingScarfBase
  id: ClothingNeckScarfStripedOrange
  name: striped orange scarf
  description: A stylish striped orange scarf. The perfect winter accessory for those with a keen fashion sense, and those who just can't handle a cold breeze on their necks.
  components:
    - type: Sprite
      sprite: Clothing/Neck/Scarfs/orange.rsi
    - type: Clothing
      sprite: Clothing/Neck/Scarfs/orange.rsi
    - type: Tag
      tags:
       - Ian # SS220 Shapochki
       - Scarf # SS220-pr: FIX CLOTHING TAGS
       - ClothMade # SS220-pr: FIX CLOTHING TAGS
       - WhitelistChameleon # SS220-pr: FIX CLOTHING TAGS
```

Посмотрел все шарфы: оффские, наши, спонсорские, базовый прототип, но ни теплового резиста, ни чего-то подобного не нашёл 😶‍🌫️
